### ISSUE TITLE
Lambda function

### ISSUE THREAD

**Issue by PriscilaProgramer07** [PriscilaProgramer07/Facial_Recognition_Attendance_System#1]
Create an AWS Lambda function. This Lambda function needs to process images uploaded to an S3 bucket, extract faces using Amazon Rekognition, and update a DynamoDB table with the detected face IDs and corresponding full names.

**Comment by Puliedro** [comment]
The images are uploaded to the S3 bucket, however, the Face ID is not being uploaded to DynamoDB, please make the necessary changes

**Comment by Puliedro** [comment]
Added Luis to help!
